version: '3'
services:
    savepet-db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=savepetapp
            - MYSQL_USER=root
            - MYSQL_PASSWORD=1234
        expose:
            - 3306
        container_name: savepet-db
        networks:
            - spring-boot-mysql-network
    savepet-app:
        build: 
            dockerfile: ./docker/app.dockerfile
            context: .
        networks:
            - spring-boot-mysql-network
        ports: 
            - "8080:8080"
        container_name: savepet-app 
        depends_on: 
            - "savepet-db"

networks:
    spring-boot-mysql-network:
        driver: bridge